import { expect, test } from './fixtures'

// PNG 1x1 válido
const PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64')

test.describe('Perfil e carteiras', () => {
  test.beforeEach(async ({ app }) => {
    await app.open('/')
    await app.loginAs('bruno')
  })

  test('edição de perfil com validação, conflito e persistência', async ({ page }) => {
    await page.goto('/account/profile')
    const form = page.getByRole('form', { name: 'Perfil do colecionador' })
    const save = form.getByRole('button', { name: 'Salvar', exact: true })
    await form.getByLabel('Nome de usuário').fill('a')
    await form.getByLabel('Nome de exibição').click()
    await expect(form.getByText('Mínimo de 3 caracteres')).toBeVisible()
    await form.getByLabel('Nome de usuário').fill('ana') // em uso
    await save.click()
    await expect(form.getByText('Este nome de usuário já está em uso.')).toBeVisible()
    await expect(form.getByLabel('Nome de usuário')).toBeFocused()

    await form.getByLabel('Nome de usuário').fill('bruno_lima')
    await form.getByLabel('Nome ENS (opcional)').fill('brunolima')
    await save.click()
    await expect(page.getByText('Perfil atualizado').first()).toBeVisible()
    await expect(form.getByRole('status')).toHaveText('Alterações salvas.')
    await page.reload()
    await expect(form.getByLabel('Nome de usuário')).toHaveValue('bruno_lima')
    await expect(form.getByLabel('Nome ENS (opcional)')).toHaveValue('brunolima')
  })

  test('avatar: envio, validação de formato e remoção', async ({ page }) => {
    await page.goto('/account/profile')
    const input = page.getByTestId('avatar-input')
    await input.setInputFiles({ name: 'doc.txt', mimeType: 'text/plain', buffer: Buffer.from('oi') })
    await expect(page.getByText('Use uma imagem PNG, JPG ou WEBP.')).toBeVisible()
    await input.setInputFiles({ name: 'grande.png', mimeType: 'image/png', buffer: Buffer.alloc(1_200_000) })
    await expect(page.getByText('A imagem deve ter no máximo 1MB.')).toBeVisible()
    await input.setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: PNG })
    await expect(page.getByText('Avatar atualizado').first()).toBeVisible()
    await page.reload()
    await expect(page.getByRole('button', { name: 'Remover' })).toBeVisible()
    await page.getByRole('button', { name: 'Remover' }).click()
    await expect(page.getByText('Avatar removido').first()).toBeVisible()
  })

  test('alteração de senha com erro da API e sucesso', async ({ page }) => {
    await page.goto('/account/profile')
    const form = page.getByRole('form', { name: 'Perfil do colecionador' })
    await form.getByLabel('Senha atual').fill('errada123')
    await form.getByLabel('Nova senha', { exact: true }).fill('curta')
    await form.getByLabel('Confirmar nova senha').fill('curta')
    await form.getByRole('button', { name: 'Salvar', exact: true }).click()
    await expect(form.getByText('A senha deve ter pelo menos 8 caracteres')).toBeVisible()
    await form.getByLabel('Nova senha', { exact: true }).fill('NovaSenha123')
    await form.getByLabel('Confirmar nova senha').fill('NovaSenha123')
    await form.getByRole('button', { name: 'Salvar', exact: true }).click()
    await expect(form.getByText('Senha atual incorreta.')).toBeVisible()
    await form.getByLabel('Senha atual').fill('Senha@123')
    await form.getByRole('button', { name: 'Salvar', exact: true }).click()
    await expect(page.getByText('Senha alterada').first()).toBeVisible()
    // a nova senha passa a valer no login
    const status = await page.evaluate(async () => (await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'bruno@nft.dev', password: 'NovaSenha123' }) })).status)
    expect(status).toBe(200)
  })

  test('carteiras principal e secundária com erros de validação', async ({ page }) => {
    await page.goto('/account/wallets')
    const primary = page.getByTestId('wallet-slot-primary')
    await primary.getByRole('button', { name: /Adicionar/ }).click()
    const form = primary.getByRole('form', { name: 'Carteira principal' })
    const save = form.getByRole('button', { name: 'Salvar carteira' })
    await form.getByLabel('Nome de exibição').fill('Bruno Lima')
    await form.getByLabel('Apelido da carteira').fill('Principal')
    await form.getByLabel('Nome do perfil').fill('Bruno Coleções')
    await form.getByLabel('E-mail').fill('bruno@nft.dev')
    await form.getByLabel('Endereço da carteira').fill('0x123')
    await save.click()
    await expect(form.getByLabel('Endereço da carteira')).toHaveAttribute('aria-invalid', 'true')
    await form.getByLabel('Endereço da carteira').fill('0x000000000000000000000000000000000000dEaD')
    await save.click()
    await expect(form.getByText('Endereço bloqueado (burn address).')).toBeVisible()
    await form.getByLabel('Endereço da carteira').fill('0x2222222222222222222222222222222222222222')
    await save.click()
    await expect(page.getByText('Carteira cadastrada').first()).toBeVisible()
    await expect(primary.getByRole('button', { name: /Adicionar|Cancelar/ })).toHaveCount(0)

    // secundária "igual à principal" com o mesmo endereço -> conflito
    const secondary = page.getByTestId('wallet-slot-secondary')
    await secondary.getByLabel('Igual à carteira principal').check()
    await secondary.getByRole('button', { name: /Adicionar/ }).click()
    const form2 = secondary.getByRole('form', { name: 'Carteira secundária' })
    await expect(form2.getByLabel('Nome de exibição')).toHaveValue('Bruno Lima')
    await form2.getByLabel('Apelido da carteira').fill('Reserva')
    await form2.getByLabel('Endereço da carteira').fill('0x2222222222222222222222222222222222222222')
    await form2.getByRole('button', { name: 'Salvar carteira' }).click()
    await expect(form2.getByText('Esta carteira já está cadastrada.')).toBeVisible()
    await form2.getByLabel('Endereço da carteira').fill('0x3333333333333333333333333333333333333333')
    await form2.getByRole('combobox', { name: 'Rede' }).click()
    await page.getByRole('option', { name: 'Polygon' }).click()
    await form2.getByRole('button', { name: 'Salvar carteira' }).click()
    await expect(secondary.getByRole('button', { name: /Adicionar|Cancelar/ })).toHaveCount(0)
    await form2.getByLabel('Apelido da carteira').fill('Reserva Polygon')
    await form2.getByRole('button', { name: 'Salvar carteira' }).click()
    await expect(page.getByText('Carteira atualizada').first()).toBeVisible()
    await page.reload()
    await expect(secondary.getByLabel('Apelido da carteira')).toHaveValue('Reserva Polygon')
    await expect(secondary.getByRole('combobox', { name: 'Rede' })).toHaveText('Polygon')
  })
})
